apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=31.41.129.22
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    # Додайте або оновіть наступні параметри для сертифікату та ключа:
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    # Інші параметри kube-apiserver
  hostNetwork: true
